### ISSUE TITLE
Pepper flash 21

### ISSUE THREAD

**Issue by KochiyaOcean** [dkwingsmt/PepperFlashFork#1]
[flash-darwin-x64.zip](https://github.com/dkwingsmt/PepperFlashFork/files/298948/flash-darwin-x64.zip)
[flash-linux-x64.zip](https://github.com/dkwingsmt/PepperFlashFork/files/298957/flash-linux-x64.zip)
[flash-win32-ia32.zip](https://github.com/dkwingsmt/PepperFlashFork/files/298958/flash-win32-ia32.zip)
[flash-win32-x64.zip](https://github.com/dkwingsmt/PepperFlashFork/files/298959/flash-win32-x64.zip)

Directory structure has changed for new version of build script.

**Comment by dkwingsmt** [comment]
Updated thx
