### ISSUE TITLE
Version 23

### ISSUE THREAD

**Issue by KochiyaOcean** [dkwingsmt/PepperFlashFork#2]
[darwin-x64.zip](https://github.com/dkwingsmt/PepperFlashFork/files/486505/darwin-x64.zip)
[linux-x64.zip](https://github.com/dkwingsmt/PepperFlashFork/files/486506/linux-x64.zip)
[win32-ia32.zip](https://github.com/dkwingsmt/PepperFlashFork/files/486507/win32-ia32.zip)
[win32-x64.zip](https://github.com/dkwingsmt/PepperFlashFork/files/486508/win32-x64.zip)

**Comment by dkwingsmt** [comment]
Updated.
